// <auto-generated />
using System;
using BackendChallenge.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendChallenge.Application.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240808175324_AddRentalEntities")]
    partial class AddRentalEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendChallenge.Application.Bikes.Bike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("license_plate");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_bikes");

                    b.HasIndex("LicensePlate")
                        .IsUnique()
                        .HasDatabaseName("ix_bikes_license_plate");

                    b.ToTable("bikes", (string)null);
                });

            modelBuilder.Entity("BackendChallenge.Application.Delivery.Deliveryman", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birthdate");

                    b.Property<string>("CnhImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cnh_image_url");

                    b.Property<string>("CnhNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("cnh_number");

                    b.Property<string>("CnhType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cnh_type");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_delivery_people");

                    b.HasIndex("CnhNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_delivery_people_cnh_number");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasDatabaseName("ix_delivery_people_cnpj");

                    b.ToTable("delivery_people", (string)null);
                });

            modelBuilder.Entity("BackendChallenge.Application.Rentals.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CostPerDay")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cost_per_day");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_in_days");

                    b.HasKey("Id")
                        .HasName("pk_plans");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("BackendChallenge.Application.Rentals.Rental", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DeliverymanId")
                        .HasColumnType("uuid")
                        .HasColumnName("deliveryman_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_rentals");

                    b.HasIndex("DeliverymanId")
                        .HasDatabaseName("ix_rentals_deliveryman_id");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_rentals_plan_id");

                    b.ToTable("rentals", (string)null);
                });

            modelBuilder.Entity("BackendChallenge.Application.Rentals.Rental", b =>
                {
                    b.HasOne("BackendChallenge.Application.Delivery.Deliveryman", "Deliveryman")
                        .WithMany()
                        .HasForeignKey("DeliverymanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rentals_deliveryman_deliveryman_id");

                    b.HasOne("BackendChallenge.Application.Rentals.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rentals_plans_plan_id");

                    b.Navigation("Deliveryman");

                    b.Navigation("Plan");
                });
#pragma warning restore 612, 618
        }
    }
}
