version: '3.8'

services:
  postgres:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: backend_challenge_db
      POSTGRES_USER: backend_challenge_user
      POSTGRES_PASSWORD: pg_b4ckendCh@llenge_ruan
      
  backendchallenge-mq:
    image: "rabbitmq:management"
    container_name: "backendchallenge-mq"
    hostname: "backendchallenge-mq"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
      - rabbitmq_data:/var/log/rabbitmq

volumes:
  postgres_data:
    driver: local

  rabbitmq_data:
    driver: local