version: '3.8'

services:
  postgres:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: backend_challenge_db
      POSTGRES_USER: backend_challenge_user
      POSTGRES_PASSWORD: pg_b4ckendCh@llenge_ruan
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  backendchallenge-mq:
    image: "rabbitmq:management"
    container_name: "backendchallenge-mq"
    hostname: "backendchallenge-mq"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
      - rabbitmq_data:/var/log/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
      
  backendchallenge-api:
    build:
      context: .
      dockerfile: BackendChallenge.Api/Dockerfile
    container_name: backendchallenge-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Database: "Host=postgres;Port=5432;Database=backend_challenge_db;Username=backend_challenge_user;Password=pg_b4ckendCh@llenge_ruan"
      ConnectionStrings__Storage: "DefaultEndpointsProtocol=https;AccountName=backendchallengestorage;AccountKey=TV6XUrtTpA1/N8di3NyandiJPGh3TXv4dQiA3OoP2jI97vk5BkhV9FQGUyBYsV9btuKYo2aOPM51+AStAwuXbQ==;EndpointSuffix=core.windows.net"
      MessageBroker__Host: "amqp://backendchallenge-mq:5672"
      MessageBroker__Username: "guest"
      MessageBroker__Password: "guest"
      Jwt__Key: "eyJhbGciOiJIUzI1NiJ9.ew0KICAic3ViIjogIjEyMzQ1Njc4OTAiLA0KICAibmFtZSI6ICJBbmlzaCBOYXRoIiwNCiAgImlhdCI6IDE1MTYyMzkwMjINCn0.PbrFwfVZh_FlZw1LMfuB3ghvBO18HRSGq_uroM5PX_w"
      Jwt__Issuer: "http://localhost:5263"
      Jwt__Audiente: "http://localhost:5263"
    ports:
      - "5263:8080"
    depends_on:
      backendchallenge-mq:
        condition: service_healthy
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local

  rabbitmq_data:
    driver: local